name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Making sure python 3.8 is installed
      run: |
        python3 --version 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv 
    - name: Installing Environment
      run: |
        pipenv sync 
    - name: Analysing the code with pylint
      run: |
        pipenv run flake8 .
